### PR TITLE
[WIP] Blogpost for `do` and `observe` functionality

### PR DESCRIPTION
**Pull request by drbenvincent**
There are notable errors here. Yet to pin down whether this is down to my use of `observe`, or if my examples are highlighting bugs that need to be fixed.

### CODE REVIEW

**Comment by ricardoV94** [comment]
CC @lucianopaz, the inline comment doesn't seem to do it: https://app.reviewnb.com/pymc-labs/research/blob/do-observe-blogpost/blog-posts%2Fdo_operator%2Fdo_operator_blogpost.ipynb/discussion/#comment-1ec9f806

**Comment by twiecki** [comment]
Just finished reading through the first draft and holy shit, this is shaping up to be a post for the ages. I think you introduce the new concepts perfectly and take the reader from where they are step by step to where they want to be. Readers will feel like that scene in the matrix where they get uploaded Kung Fu skills.

**Comment by drbenvincent** [comment]
<p>fixed</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/research/pull/3/discussion/#comment-1583137906'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/research/pull/3/discussion/#comment-1583138719'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by juanitorduz** [comment]
@drbenvincent I just wanna say I am very exited about this (and subsequent) posts! amazing team effort to bring pymc even closer to causal inference 💪 !

**Comment by ricardoV94** [comment]
The weird arrows happen when you set multiple nodes to equivalent constants (they get merged). If you set 0.00001, 0.00002, and so on, it looks alright. This hack should fix it for both `do` and `observe` if you want to preview in the notebook while I do the real fix.

It also explains why sampling was still working.

**Comment by ricardoV94** [comment]
Actually graphviz is the culprit! It triggers some graph rewrite that modifies the variables.

**Comment by ricardoV94** [comment]
There was another similar issue, for instance if one of the replacements was 1.0, because the Sigma also had one input as 1.0 and it created an artificial dependency on graphviz. Again you can fix by making it 1.000001 for now.

This should allow you to sketch the blog until that PyTensor PR is in. We can cut a release soon for the blogpost.

Also with this, you can use `observe` in that example instead of recreating the model with observed variables

**Comment by drbenvincent** [comment]
> There was another similar issue, for instance if one of the replacement values was 1.0, because the Sigma also had one input as 1.0 and it created an artificial dependency on graphviz. Again you can fix this by making the replacements odd like 1.000001 or 0.00001 (and all different from each other).
> 
> This should allow you to sketch the blog until that PyTensor PR is in. We can cut a release soon for the blogpost.

👍🏻

> Also you should be able to use `observe` in that example instead of recreating the model with observed variables. It was the same kind of problem. Or did you have another problem that was making you not use it?

So I was previously doing this:

```python
model_inference = observe(model_generative, {"c": observed['c'], "y": observed['y'], "z": observed['z']})
model_inference.set_dim("i", N, coord_values=np.arange(N))
```

That works fine when you are doing inference. 

But a problem occurs when you then go on to do something like this
```python
# P(Y | c, do(z=0))
with do(model_inference, {"z": np.zeros(N, dtype='int32')}, prune_vars=True) as model_control:
    idata_z0 = pm.sample_posterior_predictive(idata, predictions=True, var_names=["y_mu"], random_seed=SEED)
```

`model_control` looks like this

Screenshot 2023-06-16 at 16 42 24
The outcome of `sample_posterior_predictive` is as if the data for C (and maybe Y?) is no longer present.

**Comment by drbenvincent** [comment]
> There was another similar issue, for instance if one of the replacement values was 1.0, because the Sigma also had one input as 1.0 and it created an artificial dependency on graphviz. Again you can fix this by making the replacements odd like 1.000001 or 0.00001 (and all different from each other).

This approach has improved things. But there is still a connection between `beta_cy` and `c` which should not exist. `beta_cy` should only influence `c`
Screenshot 2023-06-16 at 16 49 50

**Comment by ricardoV94** [comment]
Some value must somehow still be repeated but it worked for me after the fixes so I wouldn't worry.

**Comment by drbenvincent** [comment]
Sounds like a good idea to wait for the new release before going ahead

**Comment by drbenvincent** [comment]
The graphviz issue is now fixed with the latest package versions

**Comment by drbenvincent** [comment]
> Also you should be able to use `observe` in that example instead of recreating the model with observed variables. It was the same kind of problem. Or did you have another problem that was making you not use it?

Though this does not work

**Comment by ricardoV94** [comment]
> > Also you should be able to use `observe` in that example instead of recreating the model with observed variables. It was the same kind of problem. Or did you have another problem that was making you not use it?
> 
> Though this does not work

What doesn't work? The issue with sample_posterior_predictive mentioned above is still present (i.e., posterior_predictive will always sample observed variables from the prior). That is not an "observe" issue but the expected behavior of pymc so far. Is there another problem besides that?

**Comment by drbenvincent** [comment]
At the moment we have this kind of workflow:
* define `model_generative` with no data
* use `do` to set parameters to particular values to generate `model_simulate` which we can use to generate a dataset with `sample_prior_predictive`
* create a `model_inference` from `model_generative` with `observe`, then run inference with `pm.sample`
* then finally do causal inference using the `do` function on `model_inference` and sample with `sample_posterior_predictive`. 

This final step is the one that 'doesn't work' in the sense that it doesn't give expected results given this workflow.

So to get the results I wanted I switched to this workflow:
* define `model_generative` with no data
* use `do` to set parameters to particular values to generate `model_simulate` which we can use to generate a dataset with `sample_prior_predictive`
* **CHANGED** build `model_inference` scratch, providing simulated data, then run inference with `pm.sample`. _This is suboptimal from a user workflow perspective because they are defining very similar models twice._
* then finally do causal inference using the `do` function on `model_inference` and sample with `sample_posterior_predictive`. 

So when you wrote 

> Also you should be able to use observe in that example instead of recreating the model with observed variables

I took that to mean the the first workflow would work. But I think I interpreted that wrong. But now I'm not clear on what you did mean.

Am I right in thinking that the first workflow above is not going to be possible? If so, then I think the post should forget about creating an empty model with no data and just start from a 'traditional' pymc model where we do provide simulated data. In which case the workflow would be like this:

* build `model_inference` scratch, providing simulated data, then run inference with `pm.sample`. _This is suboptimal from a user workflow perspective because they are defining very similar models twice._
* then finally do causal inference using the `do` function on `model_inference` and sample with `sample_posterior_predictive`. 

Which is fine with me, but then there will be no examples in the post where we use `observe`.

**Comment by drbenvincent** [comment]
> In any case, you don't need to recreate a new model to go get the kind of results you want right now. You can use a `do` intervention to replace the `c` observed variable by its observed values before calling `sample_posterior_predictive`. That way `y_mu` will be conditioned on the observed value of `c` instead of on its posterior_predictive draws as is now.

So if I do this, then it works in that we get the expected results.

```python
with do(model_inference, {"z": np.zeros(N, dtype='int32'), "c": df['c']}, prune_vars=True) as model_control:
    idata_z0 = pm.sample_posterior_predictive(idata, predictions=True, var_names=["y_mu"], random_seed=SEED)
```

I think I am a bit unsure why we needed to `do` the c variable because `model_generative` has already had data injected with `observe`. My internal mental model of what is happening with the type of the nodes in the graph representations is still a bit fuzzy.

But this is enough to get the blog post done. I'll double check with you that the wording is accurate once I've got a final draft together. Most likely tomorrow.

**Comment by ricardoV94** [comment]
> I think I am a bit unsure why we needed to do the c variable because model_generative has already had data injected with observe

The thing is `sample_posterior_predictive` never sees or cares about that data (in any model). 

```python
with pm.Model() as m:
  x = pm.Normal("x", 0, 1, observed=100)
  y = pm.Normal("y", 0, 1)
  det = pm.Deterministic("det", x + y)
  
  idata = pm.sample()
  pm.sample_posterior_predictive(idata, var_names=["det"])  # will always condition on new samples of `x` and not the observed value of `100`

**Comment by drbenvincent** [comment]
<p>Added</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/research/pull/3/discussion/#comment-1599296497'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Have added links to videos. </p>

---

 <a href='https://app.reviewnb.com/pymc-labs/research/pull/3/discussion/#comment-1599296518'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Good idea. Done</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/research/pull/3/discussion/#comment-1599296537'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>I've Black formatted the notebook now :)</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/research/pull/3/discussion/#comment-1599296556'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/research/pull/3/discussion/#comment-1599296594'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/research/pull/3/discussion/#comment-1599296619'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/research/pull/3/discussion/#comment-1599296643'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/research/pull/3/discussion/#comment-1599296678'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/research/pull/3/discussion/#comment-1599296692'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>I've added a short point on this</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/research/pull/3/discussion/#comment-1599296608'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Good point! I've added a new section to the introduction to briefly cover the do operator and interventions. I've stopped short of providing a full tutorial on this, but I've added some references to good resources. I plan on following up on the condition vs the interventional distribution soon so I'll come back and add a link to that when it's done.</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/research/pull/3/discussion/#comment-1599296663'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Done. I've re-ordered the examples</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/research/pull/3/discussion/#comment-1603379628'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>fixed</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/research/pull/3/discussion/#comment-1603379635'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/research/pull/3/discussion/#comment-1603379661'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Added some clarification. Also added a schematic plot at the end of the example for people to recap what we've done</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/research/pull/3/discussion/#comment-1603379675'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>Done. This was a bit lazy of me.</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/research/pull/3/discussion/#comment-1603379685'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by drbenvincent** [comment]
<p>fixed</p>

---

 <a href='https://app.reviewnb.com/pymc-labs/research/pull/3/discussion/#comment-1603379700'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by twiecki — APPROVED** [review]

**Pull request merged**
